### ISSUE TITLE
Does the draft need a Private Key section?

### ISSUE THREAD

**Issue by csosto-pk** [lamps-wg/kyber-certificates#1]
@seanturner do we need a Private Key section?

Other drafts that update RFC3279 or RFC8419 which brings a new algorithm to CMS, I did not see them including a Private Key format for any of the algorithms. 

Encoding private keys is useful to the signer, but does this specification need to define it? Wouldn't that be an update to RFC5958?

**Comment by seanturner** [comment]
@csosto-pk [RFC 3279](https://datatracker.ietf.org/doc/rfc3279/) and [RFC 8419](https://datatracker.ietf.org/doc/rfc8419/) did not, but that's why we ended up with [RFC 7468](https://datatracker.ietf.org/doc/rfc7468/) much later for RFC 3279.  You'll note nothing has been done for RFC 8419.

The curve25519 and x448 crowd went for just including it all in one, see [RFC 8410](https://datatracker.ietf.org/doc/rfc8410/).

I went for the all in one approach. I am however **_NOT_** wed to this section. I just think that it doesn't really hurt to include it.

**Comment by mouse07410** [comment]
Since this draft is not about storing (or worse - passing around) private keys in an interoperable format, IMHO it does _not_ need to define Private key format.

**Comment by seanturner** [comment]
100% agree it is _not needed_ but is there harm in including it? If we end up being unable to come to consensus on the options, then I would say it's okay to drop it. But, if we can, why not keep it.

**Comment by bwesterb** [comment]
I think a standardised private key format is required. For instance: many private keys today are generated by _certbot_ (before it fetches a certificate from it from Let's Encrypt) and then read by some webserver. _certbot_ and the webserver need to agree on the private key format.

**Comment by tarcieri** [comment]
I would agree it would be nice to have a single comprehensive document for both public and private keys and would also point to RFC8410 as an example.

Among other things RFC8410 included PKCS#8 v1 and v2 private key test vectors in their PEM encoding, which would be something nice to see in a similar RFC for ML-KEM / ML-DSA.

(Though I would hope you don't make the same mistake of including a nested inner `OCTET STRING` in the `private_key` field, which is just needless complexity)

**Comment by tarcieri** [comment]
For ML-KEM, I think it might be worth considering using a KDF to expand a smaller seed (i.e. one that matches the security level, as opposed to a 64-byte one).

Some discussion about that on pqc-forum here: https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/1r6FnG0coiM/m/I9_Jn5lJDQAJ

**Comment by bwesterb** [comment]
I agree that would be nice, and we [suggested it](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/5CT4NC_6zRI/m/lpifFrpWAwAJ) for the final version of ML-KEM. NIST didn't go for it. Now the problem is that we don't want the mess that some implementation support a 32 byte seed and others a 64 byte seed. With the 32 byte seed we don't have to think about MAL-BIND-X, but that security property has rather marginal applicability anyway. Not sure it's worth creating a mess with having two kinds of seeds.

**Comment by tarcieri** [comment]
> Now the problem is that we don't want the mess that some implementation support a 32 byte seed and others a 64 byte seed.

Unambiguously supporting both is possible, but perhaps more pain than it's worth.

**Comment by tarcieri** [comment]
I noticed https://github.com/lamps-wg/x509-slhdsa has some example PEM files: `id-slh-dsa-sha2-128s.priv` and
`id-slh-dsa-sha2-128s.pub`.

It would be nice to have something similar here.

**Comment by seanturner** [comment]
@tarcieri we added some examples.

**Comment by seanturner** [comment]
I am going to close this one out, because it looks like we have agreement to do it.

**Comment by tomato42** [comment]
I'm strongly in support of defining private key storage too, interoperability testing is one thing, but side-channel validation is another: I need to know what private key the System Under Test is using to see if its behaviour leaks part of the expanded private key. The easiest way to do it is to import externally generate private keys to it.

**Comment by seanturner** [comment]
Finally getting around to closing this out.
